# vim: set ft=dockerfile:
FROM alpine:3.18
LABEL source_repository="https://github.com/sapcc/netappsd"

RUN apk add --update curl && rm -rf /var/cache/apk/*

ENV OS=linux
ENV ARCH=amd64
ENV GOGC=100
WORKDIR /app

COPY cmd/ cmd/
COPY internal/ internal/
COPY _output/${ARCH}/netappsd netappsd
ENTRYPOINT [ "netappsd" ]
