apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: netappsd
build:
  local: {}
  platforms: ["linux/amd64"]
  artifacts:
    - image: keppel.eu-de-1.cloud.sap/ccloud/netappsd-amd64
      docker:
        dockerfile: deployments/Dockerfile-skaffold

manifests:
  rawYaml:
    - _output/netappsd.yaml

profiles:
  - name: master
    patches:
      - op: add
        path: /manifests/rawYaml/-
        value: _output/master.yaml

  - name: worker
    patches:
      - op: add
        path: /manifests/rawYaml/-
        value: _output/worker.yaml

portForward:
  - resourceType: deployment
    resourceName: netappsd-worker
    port: 13000
