apiVersion: v1
kind: ConfigMap
metadata:
  name: netappsd-deployment-template
  namespace: netapp-exporters
data:
  deployment.yaml.tpl:
    {{ file.Read "./deployments/k8s/etc/deployment.yaml.tpl" | toYAML | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netappsd-harvest
  namespace: netapp-exporters
data:
  harvest.yaml.tpl:
    {{ file.Read "./deployments/k8s/etc/harvest.yaml.tpl" | toYAML | indent 2 }}
  rest.custom.yaml:
    {{ file.Read "./deployments/k8s/etc/rest.custom.yaml" | toYAML | indent 2 }}
  rest.custom_node.yaml:
    {{ file.Read "./deployments/k8s/etc/rest.custom_node.yaml" | toYAML | indent 2 }}
  rest.custom_volume.yaml:
    {{ file.Read "./deployments/k8s/etc/rest.custom_volume.yaml" | toYAML | indent 2 }}
  rest.limited.yaml:
    {{ file.Read "./deployments/k8s/etc/rest.limited.yaml" | toYAML | indent 2 }}
  restperf.limited.yaml:
    {{ file.Read "./deployments/k8s/etc/restperf.limited.yaml" | toYAML | indent 2 }}
  start_poller.sh: |
    until [ $(find /opt/harvest/shared -name '*.yaml' | wc -l) -gt 0 ]; do
      echo "Waiting for config file to be generated"
      sleep 5
    done

    # Find the config file in ./shared and run poller in it.
    #
    # The config file is generated in ./shared by netappsd-worker, and the file name is the same as the poller name.
    exec find /opt/harvest/shared -name '*.yaml' -exec sh -c 'foo=$1; /opt/harvest/bin/poller --config $foo -p $(basename $foo .yaml)' _ {} \;
---
